### ISSUE TITLE
Timestamp on about page is incorrect

### ISSUE THREAD

**Issue by cdlewis** [baely/blog#1]
This significant decreased my enjoyment of the blog.

<img width="259" alt="Screenshot 2024-12-11 at 7 34 02 AM" src="https://github.com/user-attachments/assets/86b86eae-a724-4e21-891e-23125bd5b57e">

**Comment by baely** [comment]
Thank you for raising this and I am sorry about the degraded experience you received. I am pleased to share with you that this bug has been resolved and its fix is live in prod. I hope you can continue to enjoy https://blog.baileys.dev
